### ISSUE TITLE
Stronger backbone

### ISSUE THREAD

**Issue by kennyvoo** [Terminator8758/O2CAP#1]
Hello, great work! I've tried using a stronger backbone [transreid_base ICS](https://github.com/damo-cv/TransReID-SSL) to train the model while keeping the other parameters the same but the performance is not better than resnet50. I have attached the training logs. Can you provide some advice on this?
[vit_base_train_log.txt](https://github.com/Terminator8758/O2CAP/files/12246586/vit_base_train_log.txt)

**Comment by Terminator8758** [comment]
Hi, thanks for your interest in our work. I think when training with ViT backbone implemented by TransReID, maybe you should use the original optimizer (sgd). 
For some references on training with ViT: 
https://github.com/damo-cv/TransReID-SSL/tree/main/cluster-contrast-reid
https://github.com/RikoLi/WACV23-workshop-TMGF

**Comment by kennyvoo** [comment]
You are right! 
The result of the training with tansreid_base

```
Mean AP: 56.7%
CMC Scores:
  top-1          83.1%
  top-5          89.5%
  top-10         91.7%
```
