### ISSUE TITLE
Abnormal training results

### ISSUE THREAD

**Issue by qingsonghu08** [Terminator8758/O2CAP#2]
Why do I train according to readme and only change the batch size to 256, resulting in abnormally low performance? Is the parameter configuration incorrect? I did not make any modifications to the remaining parameters.

**Comment by Terminator8758** [comment]
Hi, the default batch size is set to 32, please try using the default batch size setting. Changing batch size may result in different performance behavior. Also, when changing batch size, num_instances and number of GPUs may have to be changed accordingly for improving performance, which we have not tried.

**Comment by qingsonghu08** [comment]
Hello, it seems that your code is based on 'Cluster Contrast for Unsupervised Person Re-Identification'. As far as I know, this code must be replicated using 4 GPUs in parallel. How did you replicate it on one GPU? Did you mainly adjust the batch size?


Terminator8758 ***@***.***> 于2023年11月24日周五 16:57写道：

**Comment by Terminator8758** [comment]
Our code is not based on Cluster Contrast. In fact, the code for O2CAP is based on our previous conference paper "Camera-Aware Proxies for Unsupervised re-ID", which came out earlier than Cluster Contrast.
